### ISSUE TITLE
TODO dec 8 2019

### ISSUE THREAD

**Issue by reidjs** [Rent-Cap/calculator#22]
- [ ] Finish About section

- [ ] Fill in protections section on /bill
- [ ] Bold active pages in nav bar
- [ ] zipcode validation for submission form
- [ ] Enable back button on eligibility flow
- [ ] Update w/ new eligibility flow
- [ ] Use zip to find cpi region
- [ ] do nav menu as absolute position instead of pushing other content down
- [ ] don't hide logo on nav menu hamburger open
- [ ] change 'rent' placeholder to 'Monthly Rent' on calc
